name: Deployment to Heroku

on:
  push:
    branches: [ main ]
    
jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          app_name: ${{ secrets.HEROKU_APP_NAME }} 
          dockerfile: :./
          options: -p 443:3000
