name: Deployment to Heroku

on:
  push:
    branches: 
      - main
    
jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
- name: Heroku Deployment
        uses: ElayGelbart/Heroku-Auto-Deployment@v1.0.6
        with:
          herokuApiKey: ${{ secrets.HEROKU_API_KEY}}
          herokuAppName: ${{ secrets.HEROKU_APP_NAME}}
          useDocker: true